# Generated by Django 4.0.3 on 2022-03-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='chave',
            new_name='chaves',
        ),
    ]
