# Generated by Django 4.0.3 on 2022-03-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_rename_chave_reserva_chaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
