# Generated by Django 4.0.3 on 2022-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
