# Generated by Django 4.0.3 on 2022-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_reserva_devolvido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
