# Generated by Django 4.0.3 on 2022-03-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_alter_reserva_data_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chapa', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='ultimo_nome',
        ),
    ]
