# Generated by Django 4.0.3 on 2022-03-31 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_pessoa_remove_reserva_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pessoas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reserva.pessoa'),
        ),
    ]
