# Generated by Django 4.0.3 on 2022-04-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_remove_pessoa_chapa_pessoa_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
