# Generated by Django 4.0.3 on 2022-09-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_alter_reserva_data_devolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='chaves',
        ),
        migrations.AddField(
            model_name='reserva',
            name='chaves',
            field=models.ManyToManyField(to='reserva.chave'),
        ),
    ]
